### ISSUE TITLE
rest.ensemblgenomes.org retired

### ISSUE THREAD

**Issue by dspeth** [DavidBSauer/OGT_prediction#1]
the genome_retriever.py script in the "prediction" directory attempts to download the genomes in the provided list from rest.ensemblgenomes.org, but fails. When opening the "http://rest.ensemblgenomes.org/info/genomes/division/EnsemblBacteria?" in a browser the following message shows up.

This REST server has been retired, please use rest.ensembl.org instead. For further information please see our blog post http://www.ensembl.info/2019/03/08/joint-rest-server-for-ensembl-and-ensembl-genomes-in-ensembl-96/

**Comment by DavidBSauer** [comment]
Thanks, I'll look into this. Clearly ensembl has changed their access mechanism since I wrote this.

**Comment by DavidBSauer** [comment]
I now have a working genome retriever working. However, for consistency it now requires the release of Ensembl to be specified.
