### ISSUE TITLE
external_tool.txt

### ISSUE THREAD

**Issue by RHarperR** [DavidBSauer/OGT_prediction#11]
Hi David~
I am trying to install the software but I had some problems when installing the python packages. I used conda to install these python packages, but when create the external_tools.txt, I didn't really get what the content of this file shold look like? Supposing that my absolute path is /home/users/.conda/envs/OGT/bin, what should the external_tool.txt look like? 

I really need your help, thank you very much, please~

**Comment by DavidBSauer** [comment]
Hello @RHarperR 
The external_tools.txt file is just a tab-delimited file for the programs used by the script: barrnap, tRNAscan-SE, bedtools, barrnap, and prodigal. Each program gets a new line where the first column is the program name. The second column is the command line used to execute the program. 

For example, here is the external_tools.txt when I've run this within a Ubuntu virtual machine (where the Ubuntu_setup.bash script will auto-install the programs).

`tRNAscan-SE tRNAscan-SE`
`bedtools bedtools`
`barrnap /home/david/OGT_prediction/External_tools/barrnap-0.9/bin/barrnap`
`prodigal prodigal`

The actual location of the programs shouldn't matter, so long as the second column is the correct command to run them.

Hope this clarifies the structure of external_tools.txt. Please let me know if I can assist further!

**Comment by DavidBSauer** [comment]
Close as stale. Please re-open if the problem reoccurs.
