### ISSUE TITLE
how to prepare genomes_retrieved.txt and species_taxonomic.txt

### ISSUE THREAD

**Issue by yyyuechen** [DavidBSauer/OGT_prediction#12]
Hi David,
Thank you so much for developing this amazing tool, however, I have some questions on how to prepare my files. I learned that I should prepare my species_taxonomic.txt and genomes_retrieved.txt as shown below:

with a custom “genomes_retrieved.txt” file 
(two tab-delimited columns, no header, columns: filename of gzip compressed contig fasta <tab> genome ID) 
and “species_taxonomic.txt” file 
(two tab-delimited columns, headers: “species <tab> superkingdom”, columns: “Genome ID <tab> Archaea|Bacteria”)

However, I am confused about what should be the genome ID and superkingdom for my MAGs, for your information, they look like this: 

.fasta file: 
k141_1435079
GTGTCTGATTGTTTTGTGATTGCGTCTTCGTAATTTTTAGAGCCTGTTTCGTCCTTCAAC
......
k141_247806
TACGATCGGCGTTCCATGGGTATCGGAACCGCTTACGAACGTGACATCATACCCCAGCTT
......
etc

and for each MAG its taxonomy looks like this:
d__Archaea;p__Halobacteriota;c__Syntropharchaeia;o__ANME-1;f__ANME-1;g__JACGMN01;s__

I tried to prepare my data as recommended:

#genome_reterieved
10_Arc_ANME-1_bin.93.fa.gz JACGMN01
45_arc_ANME-1_bin.23.fa.gz JAGXOR01
5_arc_ANME-1_bin.53.fa.gz QENH01

#species_taxonomic.txt
species superkingdom
JACGMN01 Archaea
JAGXOR01 Archaea
QENH01 Archaea
QENH01 Archaea
QENH01 Archaea
QENH01 Archaea
JACGMN01 Archaea
QENJ01 Archaea
AGXOR01 Archaea
QENJ01 Archaea

and run python3 prediction_pipeline.py ../data/prediction_demo/regression_models/ genomes_retrieved.txt species_taxonomic.txt

but I got the error:
File "/ibex/scratch/cheny0r/OGT_prediction/prediction/prediction_pipeline.py", line 63, in 
species = line.split('\t')[1].strip()
~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Can you help me to see what is the problem with my file format? Thank you so much!

**Comment by yyyuechen** [comment]
according to the demo, I generate file like this:

#genome_reterieved
10_Arc_ANME-1_bin.93.fa.gz ANME-1_JACGMN01
45_arc_ANME-1_bin.23.fa.gz ANME-1_JAGXOR01
5_arc_ANME-1_bin.53.fa.gz ANME-1_QENH01

#species_taxonomic.txt
species superkingdom phylum class order family
ANME-1_JACGMN01 Archaea	Halobacteriota Syntropharchaeia ANME-1 ANME-1
ANME-1_JAGXOR01 Archaea	Halobacteriota Syntropharchaeia ANME-1 ANME-1
ANME-1_QENH01 Archaea Halobacteriota Syntropharchaeia ANME-1 ANME-1

and run 
python3 prediction_pipeline.py ../data/prediction_demo/regression_models/ genomes_retrieved.txt species_taxonomic.txt

but I got the error: 
  File "/ibex/scratch/cheny0r/OGT_prediction/prediction/prediction_pipeline.py", line 63, in <module>
    species = line.split('\t')[1].strip()
              ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Since I can run the demo so I think this error comes from my two files, but I don't know how to prepare them now, is here any clue? the taxonomy of my mags look like this:
	domain	phylum	class	order	family	genus
10_Ch_bin.93	Archaea	Halobacteriota	Syntropharchaeia	ANME-1	ANME-1	JACGMN01
45_Ch_bin.23	Archaea	Halobacteriota	Syntropharchaeia	ANME-1	ANME-1	JAGXOR01
5_Ch_bin.53	Archaea	Halobacteriota	Syntropharchaeia	ANME-1	ANME-1	QENH01

I will really appreciate it if anyone can give any suggestions!

**Comment by DavidBSauer** [comment]
hello @yyyuechen !
A quick question: Can you double-check the file format? (It's hard to tell the formatting here on github.) Both files are expected to be TAB separated file format. If you're using another format (spaces or commas) it would fail. 

Let me know if I can help!

**Comment by yyyuechen** [comment]
> hello @yyyuechen ! A quick question: Can you double-check the file format? (It's hard to tell the formatting here on github.) Both files are expected to be TAB separated file format. If you're using another format (spaces or commas) it would fail.
> 
> Let me know if I can help!

Hi David,
Thank you for the reply! It was me that use space instead of tab to generate the file and made the problem. Thank you again!

**Comment by DavidBSauer** [comment]
Glad I could help!
