### ISSUE TITLE
regression: species trait file missing

### ISSUE THREAD

**Issue by dspeth** [DavidBSauer/OGT_prediction#3]
Hi David, 

from looking at the regression_pipeline.py script, the file required as first argument (species_trait_file) is a two column tab delimited file with species and measured OGT. I have not found such a file in the repo or associated with the paper.

The paper suggests you took the measured OGT data from your previous work (2015), so I downloaded this: http://www.med.nyu.edu/skirball-lab/dwanglab/files/thermostability_v1.1.tar.gz

There is a file in there called "all_merged_12_10_2012.txt" that seems to contain OGT data, but it contains data for 11104 species rather than the 8098 described in the 2019 paper. 
Is this the data you've used for the regression? And if so, could you provide it with this repo, so people can run the regression themselves as more genomes become available.

Personally, i am considering running the regression using the dereplicated GTDB dataset, with their updated and internally consistent taxonomy rather than the one available at NCBI. 

don't mean to be pedantic, just trying to get the most out of your work.

thanks!
Daan

**Comment by DavidBSauer** [comment]
Hi Daan,
You're right "all_merged_12_10_2012.txt" is the OGT file. 

The discrepancy in the number of species analyzed arises from: changes in species names, the species with available genomic sequences, and the OGT file including eukaryotes.

I agree, it is a bit tedious to download a separate file. But it was a matter of properly attributing prior work. As part of a prior publication, with additional co-authors, I cannot simply copy it into this repo. But I will add a more explicit comment in the README to clarify the location of this file.
