### ISSUE TITLE
Can this work with bacterial MAGs?

### ISSUE THREAD

**Issue by Anto007** [DavidBSauer/OGT_prediction#5]
This tool looks interesting. I was wondering if it can be adapted for use on bacterial metagenome-assembled-genomes (MAGs)? If so, what would be the ideal genome completeness required to predict OGT for the MAGs?

**Comment by DavidBSauer** [comment]
Great question. This is something I had in mind when doing the analysis, however I have not had time to explore MAGs.

**Comment by DavidBSauer** [comment]
I should also point out my methodology for predicting growth temperature using individual protein or nucleic acid sequences. This should be more amenable to incompletely assembled genomes. (https://github.com/DavidBSauer/protMLP and https://www.biorxiv.org/content/10.1101/677328v2)

**Comment by Anto007** [comment]
Many thanks for your prompt response! I will try to check it out soon.
