### ISSUE TITLE
Error with genome_retriever.py

### ISSUE THREAD

**Issue by morgansobol** [DavidBSauer/OGT_prediction#6]
Hi David,

I am trying to run the demo but get this error with genome_retriever.py:

Traceback (most recent call last):
  File "/pfs/data5/home/kit/ibg/fh9393/bin/OGT_prediction/prediction/genome_retriever.py", line 11, in <module>
    ref_file, setting, release = sys.argv[1:4]

I saw in a previous issue that somehow the release # needs to be specified, but do I need to do this manually?

Thanks!
Morgan

**Comment by DavidBSauer** [comment]
Hi Morgan,
Good catch! Looks like I forgot to update the README for the demo. This has now been updated. Note, the demo uses Ensembl release 40, which was also used for the paper. However, there are newer releases available.

Thanks for catching this!
David

**Comment by morgansobol** [comment]
Thanks for the fast fix for both issues!
